### ISSUE TITLE
Failure On Install

### ISSUE THREAD

**Issue by quasiben** [gpuopenanalytics/pynvml#14]
I'm tryng to install pynvml from source and getting a strange error:

```
(cudf-dev) bzaitlen@dgx15:~/GitRepos/pynvml$ pip install -e .
Obtaining file:///home/nfs/bzaitlen/GitRepos/pynvml
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/nfs/bzaitlen/GitRepos/pynvml/setup.py", line 20, in <module>
        version=versioneer.get_version(),
      File "/home/nfs/bzaitlen/GitRepos/pynvml/versioneer.py", line 1480, in get_version
        return get_versions()["version"]
      File "/home/nfs/bzaitlen/GitRepos/pynvml/versioneer.py", line 1420, in get_versions
        assert cfg.tag_prefix is not None, "please set versioneer.tag_prefix"
    AssertionError: please set versioneer.tag_prefix
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /home/nfs/bzaitlen/GitRepos/pynvml/
```

PR #13 adds versioneer but maybe something wonky happened in the setup ?

**Comment by rjzamora** [comment]
Thanks for your help here @quasiben - Looks like I merged the versioneer stuff a bit too soon

**Comment by jacobtomlinson** [comment]
Whoops sorry about that! Thanks for raising #15 @quasiben
