### ISSUE TITLE
virtual GPU has brand number =10 which is not on the list

### ISSUE THREAD

**Issue by danielbraun89** [gpuopenanalytics/pynvml#38]
my results for 
`nvidia-smi --query-gpu=name --format=csv`
are:

```
name
GRID V100DX-16Q
```

when running:
`nvidia_smi.getInstance().DeviceQuery()
`

i get:
```
Traceback (most recent call last):
  File "/home/e161081/git/comps/qalgdlinfra/QAlgDLInfra/sandbox/daniel/allegro_examples/allegro_related_scripts/gpu_debug.py", line 5, in <module>
    a = nvidia_smi.getInstance().DeviceQuery()
  File "/home/e161081/git/comps/qalgdlinfra/venv/lib/python3.8/site-packages/pynvml/smi.py", line 1886, in DeviceQuery
    brandName = NVSMI_BRAND_NAMES[nvmlDeviceGetBrand(handle)]
KeyError: 10
```

**Comment by qwertAsc** [comment]
Also having this error, after updating driver version to 460.73.01

**Comment by Riebart** [comment]
Can confirm that this is also an issue with RTX3080 Mobile GPUs, and A100 MIG partitions using a variety of drivers, tested through the official NVidia RAPIDS container images.

**Comment by dhruvdcoder** [comment]
Happens for RTX 8000 as well

```
>>> all_data= nvsmi.DeviceQuery()                                                                                                                                                                                                                                               
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".local/lib/python3.8/site-packages/pynvml/smi.py", line 2041, in DeviceQuery
    brandName = NVSMI_BRAND_NAMES[nvmlDeviceGetBrand(handle)]

KeyError: 12
```

**Comment by kenhester** [comment]
NVSMI_BRAND_NAMES updated to include additional brand names.
